name:  ðŸš¢ Release to NPM a new chat-widget version ðŸš¢

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Choose a type of release to build.
        options:
          - Patch
          - Minor

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main and pull upstream master
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Git Pull main branch 
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Create and checkout new branch
        id: create_branch
        run: |
          branch_name="release-chatwidget-bump-$(date +'%m-%d-%Y-%H-%M-%S')"
          git checkout -b "$branch_name"
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
          git push --set-upstream origin "$branch_name"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Bump Version in package.json
        id: bump_version_step
        run: |
          if [ "${{ github.event.inputs.name }}" == "Patch" ]; then
            current_version=$(jq -r '.version' chat-widget/package.json)
            patch_version=$(echo "$current_version" | cut -d. -f3)
            patch_version_final=$(echo "$patch_version" | cut -d- -f1)
            new_patch_version=$((patch_version_final))
            new_version=$(echo "$current_version" | awk -F. -v OFS=. -v patch="$new_patch_version" '{$3=patch; print}')
            jq --arg new_version "$new_version" '.version |= $new_version' chat-widget/package.json > temp.json && mv temp.json chat-widget/package.json
            echo "version=$new_version" >> $GITHUB_OUTPUT
          else
            current_version=$(jq -r '.version' chat-widget/package.json)
            major_version=$(echo "$current_version" | cut -d. -f1)
            minor_version=$(echo "$current_version" | cut -d. -f2)
            new_version="$((major_version)).$((minor_version + 1)).0"
            jq --arg new_version "$new_version" '.version |= $new_version' chat-widget/package.json > temp.json && mv temp.json chat-widget/package.json
            echo "version=$new_version" >> $GITHUB_OUTPUT
          fi

      - name: Update Changelog
        run: |
            today=$(date +'%Y-%m-%d')
            version="${{ steps.bump_version_step.outputs.version }}"
            sed -i "0,/\[Unreleased\]/s/\[Unreleased\]/[${version}] ${today}/" CHANGE_LOG.md

      - name: Commit Changes
        run: |
          git config --global user.email "elopezanaya@gmail.com"
          git config --global user.name "elopezanaya"
          git add chat-widget/package.json CHANGE_LOG.md
          git commit -m "Bump version to ${{ steps.bump_version_step.outputs.version }}"

          git tag -a "TEST-v${{ steps.bump_version_step.outputs.version }}" -m "Version ${{ steps.bump_version_step.outputs.version }}"
          git push origin "TEST-v${{ steps.bump_version_step.outputs.version }}"
  
      - name: Bump Version in package.json
        id: bump_version_step_minor
        run: |
            if [ "${{ github.event.inputs.name }}" == "Patch" ]; then
              current_version=$(jq -r '.version' chat-widget/package.json)
              patch_version=$(echo "$current_version" | cut -d. -f3)
              new_patch_version=$((patch_version + 1))-0
              new_version=$(echo "$current_version" | awk -F. -v OFS=. -v patch="$new_patch_version" '{$3=patch; print}')
              jq --arg new_version "$new_version" '.version |= $new_version' chat-widget/package.json > temp.json && mv temp.json chat-widget/package.json
              echo "version=$new_version" >> $GITHUB_OUTPUT
            else
              current_version=$(jq -r '.version' chat-widget/package.json)
              patch_version=$(echo "$current_version" | cut -d. -f3)
              new_patch_version=$((patch_version + 1))-0
              new_version=$(echo "$current_version" | awk -F. -v OFS=. -v patch="$new_patch_version" '{$3=patch; print}')
              jq --arg new_version "$new_version" '.version |= $new_version' chat-widget/package.json > temp.json && mv temp.json chat-widget/package.json
              echo "version=$new_version" >> $GITHUB_OUTPUT
            fi

      - name: Search for 'Chat Widget' tag and add '##[Unreleased]'
        run: |
          # Find the line number where 'Chat-Widget' tag is located in the file
          line_number=$(grep -n 'Chat-Widget' CHANGE_LOG.md | cut -d':' -f1)
          
          if [ -n "$line_number" ]; then
          # Increment line number by 1 to add '##[Unreleased]' below the 'Chat Widget' tag
            new_line_number=$((line_number + 1))
            sed -i "${new_line_number}i## [Unreleased] \n" CHANGE_LOG.md
            # git add CHANGE_LOG.md
            # git commit -m "Bump"
          else
            echo "Tag 'Chat-Widget' not found in CHANGE_LOG.md"
          fi

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: main
          branch: ${{ steps.create_branch.outputs.branch_name }}
          delete-branch: true
          title: 'Bump version for chat-widget to ${{ steps.bump_version_step.outputs.version }}'
          body: |
            Update report
            - 'Bump version to ${{ steps.bump_version_step.outputs.version }}'
          labels: |
            bump-release-version
            automated pr
            chat-widget
          draft: false
