name: chat-widget-pr

on:
  pull_request:
    branches:
      - '**'
    types: [edited, assigned, opened, synchronize, reopened]
    paths:
      - 'chat-widget/**'

permissions:
  contents: read
  pull-requests: write
      
jobs: 
  build:
    runs-on: windows-2019
    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.X
      - name: Install packages
        working-directory: chat-widget
        run: yarn install
      - name: Install playwright jest packages
        working-directory: chat-widget/automation_tests
        run: yarn install
      - name: Unit Tests
        working-directory: chat-widget
        run: yarn test:unit
      - name: E2E Tests
        working-directory: chat-widget/automation_tests
        run: yarn test
      - name: Build Storybook
        working-directory: chat-widget
        env :
          NODE_OPTIONS: --openssl-legacy-provider
        run : yarn build-storybook
      - name: VRT Tests
        working-directory: chat-widget
        run: yarn test:visual
      - name: Upload VRT Tests failures screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: VRT Failure Screenshots
          path: 'chat-widget/**/__diff_output__/*.png'
      - name: Build package
        working-directory: chat-widget
        run: yarn build
